{
  'version': '0.2',
  'phases':
    {
      'pre_build': { 'commands': ['npm i -g npm && npm ci'] },
      'build': { 'commands': ['npx cdk synth'] },
    },
  'artifacts': { 'base-directory': 'cdk.out', 'files': '**/*' },
}
